name = "maven-proxy"
type = "javascript"
main = "src/proxy.js"

workers_dev = true
compatibility_date = "2023-10-01"

[build]
upload.format = "service-worker"
[vars]
# MAVEN_REPO_URL = "https://repo.maven.apache.org/maven2/"
CACHE_TTL = "2592000"
